ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pin_hash VARCHAR(255),
    ADD COLUMN IF NOT EXISTS salt VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_type VARCHAR(50) NOT NULL DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS is_first_login BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    DROP COLUMN IF EXISTS player_id,
    DROP COLUMN IF EXISTS email,
    DROP COLUMN IF EXISTS hashcode;

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_name ON users(name);
