CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    pin_hash VARCHAR(255),
    salt VARCHAR(255),
    user_type VARCHAR(50) NOT NULL DEFAULT 'USER',
    is_first_login BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
